<?php

namespace AppBundle\Repository;

/**
 * productSoortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productSoortRepository extends \Doctrine\ORM\EntityRepository
{
}
